In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
# one dimensional array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
# two dimensional array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# accessing the elements of numpy array
a=np.array([1,2,3,4,5])
# .shape will indicate the dimension of that array
print(a.shape)

b=np.array([[1,2,3],[4,5,6]])
print(b.shape)# here (2,3) represents the array has 2 rows and 3 columns...
print(b)

# accessing the elements based on indexing number
print(a[0],a[1],a[2],a[3])



(5,)
(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 3 4


In [8]:
# changing an element of the array
a=np.array([1,2,3,4,5])
a[0]=143
a[4]=1432
print(a)

[ 143    2    3    4 1432]


In [9]:
# accessing elements by giving row and column values(R,C)
b=np.array([[1,2,3],[4,5,6]])
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [10]:
#coverting a list into an array by using array() function
hi=[11,22,33,44,55]
hi=np.array(hi)
print(hi)
bye=[['a','b','c','d','e','f'],['g','h','i','j','k','l']]
bye=np.array(bye)
print(bye)

[11 22 33 44 55]
[['a' 'b' 'c' 'd' 'e' 'f']
 ['g' 'h' 'i' 'j' 'k' 'l']]


In [11]:
# creating a array by using arange() function
# arange(1,10,2) here 1 represents starting value(),10 represents ending value(),2 represents step value()
c=np.arange(1,10,2)
print(c)

c1=np.arange(1,10,1.5)
print(c1)

# if third value is not given then by default step size =1
d=np.arange(1,10)
print(d)

# suppose if the 1st value and 3rd value are not given then by default start=0 and step=1
e=np.arange(10)
print(e)

[1 3 5 7 9]
[1.  2.5 4.  5.5 7.  8.5]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
#using ndim function:
#identifying whether it is a 2-D OR 3-D array.
#in 2-D array we are accessing the elements by giving array[row],[col]
# in 3-D array by giving array[layer],[row],[col]

b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)
b1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b1.ndim)

2
3


In [13]:
# using .shape function
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
b1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b1.shape)

(2, 3)
(2, 2, 3)


In [3]:
#resize the array
b=np.array([[1,2,3],[4,5,6]])
b.shape=(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
# .size function
b=np.array([[1,2,3],[4,5,6]])
print(b.size)
b1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b1.size)

6
12


In [16]:
# .dtype function
a=np.array([1,2,3,4,5])
print(a.dtype)
a1=np.array([1.1,2.2,3.3,4.4])
print(a1.dtype)

int32
float64


In [17]:
# .itemsize function
a=np.array([1,2,3,4,5])
print(a.itemsize)
a1=np.array([1.1,2.2,3.3,4.4])
print(a1.itemsize)

4
8


In [18]:
#slicing based on indexing number
s=np.array([10,20,30,40,50,60,70,80])
print(s[2:6:2])
print(s[:])
print(s[-2:])
print(s[-1:-4:-1])

[30 50]
[10 20 30 40 50 60 70 80]
[70 80]
[80 70 60]


In [19]:
#reshaping an array
s1=np.arange(12)
print(s1)
s1=s1.reshape(3,4)
print(s1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# coverting 1-d array to 2-d and 3-d arrays
s1=np.arange(8)
print(s1)
s1=s1.reshape(2,4)
print(s1)
s1=s1.reshape(2,2,2) # 1st 2 represents layer,2 represents row and 2 represents col...
print(s1)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [21]:
# array concatenation(1-dimensional)
q=np.array([1,2,3])
w=np.array([4,5,6])
e=np.concatenate((q,w))
print(e)

# joining multidimensional arrays
r=np.array([[1,2],[3,4]])
t=np.array([[11,12],[13,14]])
y=np.concatenate((r,t))
print(y)

# by using axis =1 
r=np.array([[1,2],[3,4]])
t=np.array([[11,12],[13,14]])
y=np.concatenate((r,t),axis=1)
print(y)


[1 2 3 4 5 6]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
[[ 1  2 11 12]
 [ 3  4 13 14]]


In [22]:
# horizontal stacking(stack along rows)
q=np.array([1,2,3])
w=np.array([4,5,6])
r=np.array([7,8,9])
e=np.hstack((q,w,r))
print(e)

[1 2 3 4 5 6 7 8 9]


In [23]:
# vertical stacking(stack along columns)
q=np.array([1,2,3])
w=np.array([4,5,6])
r=np.array([7,8,9])
e=np.vstack((q,w,r))
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# height stacking
q=np.array([1,2,3,4])
w=np.array([4,5,6,7])
e=np.dstack((q,w))
print(e)

[[[1 4]
  [2 5]
  [3 6]
  [4 7]]]


In [25]:
# spilting of an array
s=np.array([10,20,30,40,50,60,70,80])
z=np.array_split(s,15)
print(z)

[array([10]), array([20]), array([30]), array([40]), array([50]), array([60]), array([70]), array([80]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [26]:
# spil 7iting along rows in 2-dimensional
r=np.array([[1,2],[3,4],[5,6],[7,8]])
r1=np.hsplit(r,2)
print(r1)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [27]:
# spiliting along columns in 2-d
r=np.array([[1,2],[3,4],[5,6],[7,8]])
r1=np.vsplit(r,2)
print(r1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [28]:
# these universal functions we are using to calculate mathematical operations(trigonometric,exponential and logarithms)
# statistical (mean,median,mode,s.d,percentile),bitwise and comparasion operations etc....

x=np.array([1,2,3,4,5])
y=np.array([10,20,30,40,50])
z=np.add(x,y)
z1=np.subtract(y,x)
z2=np.multiply(x,y)
z3=np.divide(x,y)
z4=np.power(y,x)
z5=np.sum(x)
z6=np.product(x)
z7=np.sin(x)
# similarly min(),max(),sqrt(),abs(),exp(),log(),sin(),cos(),tan(),arcsin(),arcos(),arctan()
print(z)
print(z1)
print(z2)
print(z3)
print(z4)
print(z5)
print(z6)
print(z7)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[       10       400     27000   2560000 312500000]
15
120
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [29]:
# save() function it saves an array to a binary file in the numpy  .npy format
x1=np.array([[1,3,5],[2,4,6]])
np.save('file.npy',x1)

In [30]:
# loading the binary file 
hii=np.load('file.npy')
print(hii)

[[1 3 5]
 [2 4 6]]


In [31]:
# .savetxt() it saves an array to a text file
x1=np.array([[1,3,5],[2,4,6]])
np.savetxt('file.txt',x1)

In [32]:
# .loadtxt() it loads the savedtxt file 
hii=np.loadtxt('file.txt')
print(hii)

[[1. 3. 5.]
 [2. 4. 6.]]


In [33]:
# linear algebra
j=np.array([1,3,5])
k=np.array([2,4,6])
result=np.dot(j,k)
print(result)
# 2d array to 1d array by suing inner() function
a=np.array([[1,2],[5,6]])  # [1*3+2*4     1*7+2*8
b=np.array([[3,4],[7,8]])  # 5*3+6*4     5*7+6*8]
r1=np.inner(a,b)
print(r1)

j=np.array([1,3,5])   # [1*2 1*4 1*6
k=np.array([2,4,6])   # 3*2 3*4 3*6
result=np.outer(j,k)  # 5*2 5*4 5*6]
print(result)

44
[[11 23]
 [39 83]]
[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [34]:
#linalg module
# calculating the determinent of matrix
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.det(n))

# inverse of a matrix
print(np.linalg.inv(n))

# trace of a matrix
print(np.trace(n))

-9.51619735392994e-16
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
15


In [37]:
# generating the random integer and float values
i=np.random.randint(100)
print(i)
# getting a floating value in between 0 to 1
f=np.random.rand(2)
print(f)

6
[0.81947162 0.39616399]


In [5]:
# generating random array
# here we generating 4 random integers in between 0 to 99
d=np.random.randint(0,100,4)
print(d)

# generating a 3 by 3 matrix containing a floating values in between 0 to 1
v=np.random.rand(2,2)
print(v)

[89 75 88 57]
[[0.51345516 0.42152745]
 [0.1040529  0.1400292 ]]


In [18]:
# seed will give you everytime the same random numbers 
np.random.seed(40)
f=np.random.randint(0,100,5)
print(f)

[70 91  7 37 56]
